In [3]:
import pandas as pd
import numpy as np

In [7]:
redwine = pd.read_csv("C:\\Users\\hp\\Desktop\\Python n DS\\winequality-red.csv", sep = ";")

In [8]:
whitewine = pd.read_csv("C:\\Users\\hp\\Desktop\\Python n DS\\winequality-white.csv", sep = ";")

In [10]:
redwine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [11]:
redwine.shape

(1599, 12)

In [12]:
redwine['color'] = 'Red'

In [13]:
redwine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red

In [15]:
redwine['color1'] = ['Red' for i in range(0,1599)]

In [17]:
redwine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color,color1
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red,Red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red,Red

In [ ]:
redwine.drop('color1',axis=1, inplace = True)

In [21]:
redwine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red

In [22]:
whitewine['color'] = 'White'

In [24]:
whitewine.shape

(4898, 13)

In [23]:
whitewine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,White
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,White
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,White
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White

In [26]:
pd.concat([redwine,whitewine], axis = 0, join = 'outer').head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red

In [27]:
pd.concat([redwine,whitewine], axis = 1, join = 'outer').head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,...,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,...,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,White
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,...,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,White
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,...,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,White
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,...,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,...,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White

In [43]:
output_data = pd.concat([redwine,whitewine], axis = 0, join = 'outer', keys = [1,2])

In [53]:
output_data[(output_data['color'] == 'Red') & (output_data['pH'] > 3.0)].head(10)

     fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1 0            7.4              0.70         0.00             1.9      0.076
  1            7.8              0.88         0.00             2.6      0.098
  2            7.8              0.76         0.04             2.3      0.092
  3           11.2              0.28         0.56             1.9      0.075
  4            7.4              0.70         0.00             1.9      0.076
  5            7.4              0.66         0.00             1.8      0.075
  6            7.9              0.60         0.06             1.6      0.069
  7            7.3              0.65         0.00             1.2      0.065
  8            7.8              0.58         0.02             2.0      0.073
  9            7.5              0.50         0.36             6.1      0.071

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1 0                 11.0                  34.0   0.9978  3.51       0.56
  1                 25.0                  67.0   0.9968  3.20       0.68
  2                 15.0                  54.0   0.9970  3.26       0.65
  3                 17.0                  60.0   0.9980  3.16       0.58
  4                 11.0                  34.0   0.9978  3.51       0.56
  5                 13.0                  40.0   0.9978  3.51       0.56
  6                 15.0                  59.0   0.9964  3.30       0.46
  7                 15.0                  21.0   0.9946  3.39       0.47
  8                  9.0                  18.0   0.9968  3.36       0.57
  9                 17.0                 102.0   0.9978  3.35       0.80

     alcohol  quality color
1 0      9.4        5   Red
  1      9.8        5   Red
  2      9.8        5   Red
  3      9.8        6   Red
  4      9.4        5   Red
  5      9.4        5   Red
  6      9.4        5   Red
  7     10.0        7   Red
  8      9.5        7   Red
  9     10.5        5   Red

In [54]:
output_data.sort_values('pH', ascending = False).head(10)

        fixed acidity  volatile acidity  citric acid  residual sugar  \
1 1316            5.4             0.740         0.00            1.20
  1321            5.0             0.740         0.00            1.20
  695             5.1             0.470         0.02            1.30
  45              4.6             0.520         0.15            2.10
  95              4.7             0.600         0.17            2.30
2 1250            5.3             0.260         0.23            5.15
  1255            6.4             0.220         0.34            1.80
  2771            6.3             0.200         0.24            1.70
  2036            5.7             0.270         0.32            1.20
  2321            4.6             0.445         0.00            1.40

        chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
1 1316      0.041                 16.0                  46.0  0.99258  4.01
  1321      0.041                 16.0                  46.0  0.99258  4.01
  695       0.034                 18.0                  44.0  0.99210  3.90
  45        0.054                  8.0                  65.0  0.99340  3.90
  95        0.058                 17.0                 106.0  0.99320  3.85
2 1250      0.034                 48.0                 160.0  0.99520  3.82
  1255      0.057                 29.0                 104.0  0.99590  3.81
  2771      0.052                 36.0                 135.0  0.99374  3.80
  2036      0.046                 20.0                 155.0  0.99340  3.80
  2321      0.053                 11.0                 178.0  0.99426  3.79

        sulphates  alcohol  quality  color
1 1316       0.59     12.5        6    Red
  1321       0.59     12.5        6    Red
  695        0.62     12.8        6    Red
  45         0.56     13.1        4    Red
  95         0.60     12.9        6    Red
2 1250       0.51     10.5        7  White
  1255       0.57     10.3        6  White
  2771       0.66     10.8        6  White
  2036       0.41     10.2        6  White
  2321       0.55     10.2        5  White

In [56]:
output_data[(output_data['color'] == 'Red') & (output_data['pH'] > 4)].head()

        fixed acidity  volatile acidity  citric acid  residual sugar  \
1 1316            5.4              0.74          0.0             1.2
  1321            5.0              0.74          0.0             1.2

        chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
1 1316      0.041                 16.0                  46.0  0.99258  4.01
  1321      0.041                 16.0                  46.0  0.99258  4.01

        sulphates  alcohol  quality color
1 1316       0.59     12.5        6   Red
  1321       0.59     12.5        6   Red